## Overview

In this PA, you will will be creating and manipulating basic objects to uncover a top secret message.

### Hint 1

As you work through this PA, you will encounter some code that does not work as you want it to.  Don't despair!  Errors (when R is unable to run your code) and bugs (when the code doesn't do what you hoped) are a natural part of coding.  Even the best of the best deal with these problems regularly - learning to track down the issue is a skill that you can learn and practice.

Google is your friend!  If an error is confusing, copy it into Google and see what other people are saying.  If you don't know how to do something, search for it.

### Hint 2

Just because there is no error message doesn't mean everything went smoothly.  You should be regularly printing out your objects, to see they contain the information and format that you expect.

For example, if you have an object named `my_thing`, you might first want to simply look at the object by typing its name.

However, you might also want to make sure it is the right **object type** and/or the right **object structure**.


In [ ]:
type(my_thing)
len(my_thing)

## Part One: Setup

Each of the following code chunks will cause an error and/or do the desired task incorrectly.  Find the mistake, and correct it to complete the intended action.




1. Create lists containing the upper case letters, lower case letters, and some punctuation marks.


In [ ]:
lower_case = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]

upper_case = ["A", "B", "C", "D", "E", "F", "G", "H" "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

punctuation = [".", ",", "!", "?", "'", "\"", "(", ")", " ", "-", ";", ":"]

2. Make one long list containing all the symbols.  Find the length of this list.


In [ ]:
all_symbols = lower_case + upper_case + punctuation

len(all_symbols)

63

3. Repeat the previous steps, but instead of using *list* type objects, use **numpy arrays**.  Don't forget to **import** the numpy library!


In [ ]:
import numpy as np

lower_case = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"])

upper_case = np.array(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"])

punctuation = np.array([".", ",", "!", "?", "'", "\"", "(", ")", " ", "-", ";", ":"])

## Use np.concatenate to combine into long array
all_symbols = np.concatenate((lower_case, upper_case, punctuation))

4. Make a **pandas data frame**, with one column called "Symbol" containing the `all_symbols` array.


In [ ]:
import pandas as pd

symbols_df = pd.DataFrame(all_symbols)

symbols_df = symbols_df.rename(columns = {0:"Symbol"})


## Part Two: Decoding the secret message.


In [ ]:
top_secret = pd.read_csv("https://www.dropbox.com/s/k72h1zewk4gtqep/PA_Secret_Code?dl=1", header=None)

top_secret = top_secret[0].to_numpy()

print(top_secret[:20])
len(top_secret)

[0.39104271 0.38644508 0.37131377 0.33881179 0.37131377 0.39695721
 0.35479413 0.37573224 0.3693288  0.37404822 0.37573224 0.37490299
 0.37490299 0.40018665 0.40307943 0.37490299 0.38531114 0.38024665
 0.40542    0.39915133]


955

### Hint

Recall that basic math operations are **vectorized**.  This means you don't have to repeat the process for each item in a list; you can apply the math to the whole thing at once.

### Instructions

By altering this top secret set of numbers, you will be able to create a message.  Write your own code to complete the steps below.

1. Add 14 to every number.
2. Multiply every number by 18, then subtract 257.
3. Exponentiate every number.  (That is, do e^[number].  You may have to Google how to do this!)
4. Square every number.

**Checkpoint:** Headquarters has informed you that at this stage of decoding, there should be 352 numbers in the secret message that are below 17.  Write code to check if this is true for your data.


5. Turn your one-dimensional array of numbers into a two-dimensional array (matrix) with 5 columns. This conversion should be **column-wise**; that is, the first several elements of the array should all end up in the first **column** of your matrix.
6. Separately from your top secret numbers, create an array of all the even numbers between 1 and 382. Name it "evens". That is, "evens" should contain 2, 4, 6, 8 ..., 382.
7. Subtract the "evens" vector from the first column of your secret message matrix.
8. Subtract 100 from all numbers in the 18-24th rows of the 3rd column.
9. Multiply all numbers in the 4th and 5th column by 2.
10. Turn your matrix back into a one dimensional array. Again this should be **column-wise**, so that the first column of the matrix becomes the first elements of the array.


**Checkpoint:** Headquarters has informed you that at this stage of decoding, all numbers in indices 500 and beyond are below 100.  Write code to check if your numbers fulfill this requirement.

11. Take the square root of all numbers in indices 37 to 464.
12. Round all numbers to the nearest whole number.
13. Replace all instances of the number 39 with 20.

**Checkpoint:** Headquarters has informed you that your final message should have 344 even numbers.  Write code to check if your numbers fulfill this requirement.

## Part 3: The secret message!

Run the following to discover the final message!  Google the first line of this message, if you do not recognize it, to see what it is.


In [ ]:
# step 1,2
top_secret_1_2 = (top_secret + 14) * 18 - 257
print(top_secret_1_2[:10])

[2.03876872 1.9560115  1.68364791 1.09861229 1.68364791 2.14522972
 1.38629436 1.76318026 1.64791843 1.73286795]


In [ ]:
# step 3
top_secret_exp = np.exp(top_secret_1_2)
print(top_secret_exp[:10])

[7.68114575 7.07106781 5.38516481 3.         5.38516481 8.54400375
 4.         5.83095189 5.19615242 5.65685425]


In [ ]:
# step 4
top_secret_power2 = np.power(top_secret_exp, 2)
print(top_secret_power2[:10])
len(top_secret_power2)

[59. 50. 29.  9. 29. 73. 16. 34. 27. 32.]


955

In [ ]:
# checkpoint
num_below_17 = np.sum(top_secret_power2 < 17)
print(num_below_17)

352


In [ ]:
# turn it in
top_secret_matrix_5 = top_secret_power2.reshape(-1, 5, order= 'F')
print(top_secret_matrix_5[:5])

[[5.900e+01 1.440e+02 3.610e+02 9.000e+00 2.050e+01]
 [5.000e+01 1.000e+00 1.521e+03 7.500e+00 3.050e+01]
 [2.900e+01 5.290e+02 2.250e+02 1.050e+01 3.000e+00]
 [9.000e+00 3.610e+02 2.250e+02 3.500e+00 9.000e+00]
 [2.900e+01 3.721e+03 1.600e+01 4.000e+00 5.000e-01]]


In [ ]:
evens = np.arange(2, 384, 2)
print(evens)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214 216
 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250 252
 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286 288
 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322 324
 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358 360
 362 364 366 368 370 372 374 376 378 380 382]


In [ ]:
top_secret_matrix_5[:,0] -= evens

In [ ]:
top_secret_matrix_5[17:24, 2] -= 100

In [ ]:
top_secret_matrix_5[:, [3, 4]] *= 2

In [ ]:
print(top_secret_matrix_5)

In [ ]:
top_secret = top_secret_matrix_5.reshape(-1, order="F")

In [ ]:
# checkpoint
num_below_500 = np.sum(top_secret[500:] > 100)
print(num_below_500)

0


In [ ]:
len(top_secret)

955

In [ ]:
top_secret[37:465] = np.sqrt(top_secret[37:465])
len(top_secret)

955

In [ ]:
top_secret = np.round(top_secret)
len(top_secret)

955

In [ ]:
top_secret = np.where(top_secret == 39, 20, top_secret)
len(top_secret)

955

In [ ]:
# checkpoint
num_below_even = top_secret[top_secret % 2 == 0]
len(num_below_even)

344

In [ ]:
''.join(map(str, symbols_df.loc[top_secret-1]['Symbol']))

'\'Twas brillig, and the slithy toves   Did gyre and gimble in the wabe: All mimsy were the borogoves,   And the mome raths outgrabe. "Beware the Jabberwock, my son!   The jaws that bite, the claws that catch! Beware the Jubjub bird, and shun   The frumious Bandersnatch!" He took his vorpal sword in hand;   Long time the manxome foe he sought- So rested he by the Tumtum tree   And stood awhile in thought. And, as in uffish thought he stood,   The Jabberwock, with eyes of flame, Came whiffling through the tulgey wood,   And burbled as it came! One, two! One, two! And through and through   The vorpal blade went snicker-snack! He left it dead, and with its head   He went galumphing back. "And hast thou slain the Jabberwock?   Come to my arms, my beamish boy! O frabjous day! Callooh! Callay!"   He chortled in his joy. \'Twas brillig, and the slithy toves   Did gyre and gimble in the wabe: All mimsy were the borogoves,   And the mome raths outgrabe.'